### ISSUE TITLE
Skipping white space

### ISSUE THREAD

**Issue by ghost** [richard-lyman/amotoen#5]
Hi, amotoen in quite a relief given my previous experience of using Antlr from Clojure (I never needed something that sophisticated). I've been experimenting with amotoen for a while now. I'm just wondering if there is a way to intersperse whitespace between every token by a single rule? The manual insertion of `:_*` will be tedious given the number of rules in the grammar I'm dealing with. Thanks !

**Comment by richard-lyman** [comment]
Complete transition to a new implementation. The new implementation takes an approach with whitespace that is similar to the previous one - you would need to specify the whitespace. However, it would not be too difficult to wrap the base States with something that injects whitespace as needed.
